// words.js - 高一必修单词库
const wordData = {
    unit1: {
        topicTalk: [
            { english: "senior", chinese: "较高的，高级的" },
            { english: "secondary", chinese: "中等教育；中级的；次要的" },
            { english: "stressful", chinese: "充满压力的，紧张的" },
            { english: "challenging", chinese: "富有挑战性的" },
            { english: "differ", chinese: "不同，不一样，有区别" },
            { english: "previous", chinese: "以前的，先前的" },
            { english: "dynamic", chinese: "充满活力的；精力充沛的" },
            { english: "campus", chinese: "校园" },
            { english: "schedule", chinese: "日程表，计划表" },
            { english: "expectation", chinese: "期待；预料，预期" },
            { english: "confidence", chinese: "自信，信心；信赖" },
            { english: "competence", chinese: "能力，胜任" },
            { english: "chapter", chinese: "一段时期；章节" },
            { english: "all in all", chinese: "总而言之，总的来说" },
            { english: "apartment", chinese: "公寓套房" },
            { english: "am", chinese: "午前，上午" },
            { english: "shift", chinese: "（工厂、医院等轮班制的）当班时间" },
            { english: "pressure", chinese: "压力" },
            { english: "leisure", chinese: "空闲，闲暇，业余时间" },
            { english: "recover", chinese: "恢复健康，康复" },
            { english: "injury", chinese: "伤，损害" },
            { english: "plus", chinese: "有利的，好的；加" },
            { english: "unfortunately", chinese: "不幸地；令人遗憾地" },
            { english: "challenge", chinese: "挑战；具有挑战性的事物；向……挑战" },
            { english: "arise", chinese: "（问题或困难）出现，发生" }
        ],
        lesson1: [
            { english: "lifestyle", chinese: "生活方式" },
            { english: "chat", chinese: "闲谈，聊天" },
            { english: "surf", chinese: "冲浪" },
            { english: "surf the Internet", chinese: "网上冲浪，浏览因特网" },
            { english: "voluntary", chinese: "志愿的；服务的；自愿的" },
            { english: "engine", chinese: "引擎" },
            { english: "search engine", chinese: "搜索引擎" },
            { english: "definitely", chinese: "确切地，肯定地" },
            { english: "teen", chinese: "少年，十几岁的孩子" },
            { english: "laptop", chinese: "笔记本电脑，便携式电脑" },
            { english: "digital", chinese: "数字的，数码的" },
            { english: "native", chinese: "本地人" },
            { english: "range", chinese: "一系列；范围" },
            { english: "various", chinese: "各种各样的；多种（类型）的" },
            { english: "hardware", chinese: "（计算机）硬件" },
            { english: "necessity", chinese: "必需品" },
            { english: "convenient", chinese: "方便的，便利的" },
            { english: "quality", chinese: "质量，品质" },
            { english: "from time to time", chinese: "有时；偶尔；间或" },
            { english: "living room", chinese: "起居室" },
            { english: "addict", chinese: "对……着迷的人" },
            { english: "according to", chinese: "按……所说，根据" },
            { english: "in person", chinese: "亲自" },
            { english: "media", chinese: "新闻媒体，大众传播媒介（总称）" },
            { english: "social media", chinese: "社交媒体" },
            { english: "actually", chinese: "实际上，事实上" },
            { english: "drag", chinese: "拖，拉" },
            { english: "tend to do sth", chinese: "易于做某事" },
            { english: "goal", chinese: "目标，目的" },
            { english: "aim", chinese: "目的，意图；力求达到" },
            { english: "target", chinese: "目标" },
            { english: "update", chinese: "更新" },
            { english: "*meanwhile", chinese: "与此同时" },
            { english: "distance", chinese: "距离，间距" },
            { english: "volunteer", chinese: "自愿；志愿；志愿者" },
            { english: "revise", chinese: "复习" },
            { english: "saying", chinese: "格言，谚语" },
            { english: "ahead", chinese: "在前面；向前" },
            { english: "get ahead", chinese: "取得进步，获得成功" }
        ],
        lesson2: [
            { english: "café", chinese: "咖啡馆，小餐馆" },
            { english: "downtown", chinese: "向 / 在城镇商业中心区" },
            { english: "stress", chinese: "压力；忧虑；紧张" },
            { english: "suffer", chinese: "遭受（痛苦）" },
            { english: "suffer from", chinese: "（身体或精神上）遭受……（痛苦）" },
            { english: "reduce", chinese: "减少；降低；缩小" },
            { english: "expert", chinese: "专家，行家" },
            { english: "frank", chinese: "坦率的，坦诚的" },
            { english: "to be frank", chinese: "坦白说，坦率地说" },
            { english: "editor", chinese: "编辑，主编" },
            { english: "remove", chinese: "移走；去掉" },
            { english: "entirely", chinese: "完全地，彻底地" },
            { english: "position", chinese: "职位；位置" },
            { english: "military", chinese: "军队，武装力量" },
            { english: "due to", chinese: "因为" },
            { english: "absolutely", chinese: "正是，当然" },
            { english: "stressed", chinese: "焦虑的，紧张的" },
            { english: "extent", chinese: "程度" },
            { english: "thus", chinese: "因此，因而，从而" },
            { english: "tension", chinese: "紧张；焦虑" },
            { english: "organise", chinese: "组织，筹划" },
            { english: "in other words", chinese: "换句话说" },
            { english: "function", chinese: "运转，工作；功能" },
            { english: "seek", chinese: "寻求；请求" },
            { english: "professional", chinese: "专业的，职业的" }
        ],
        lesson3: [
            { english: "feature", chinese: "以……为特色，是……的特征" },
            { english: "typical", chinese: "平常的，一贯的；典型的" },
            { english: "province", chinese: "省" },
            { english: "graduate", chinese: "毕业" },
            { english: "graduate from", chinese: "从……毕业" },
            { english: "certificate", chinese: "合格证书" },
            { english: "inspire", chinese: "鼓励，激励" },
            { english: "apply", chinese: "申请；请求" },
            { english: "eager", chinese: "热切的；渴望的" },
            { english: "sort", chinese: "种，类；类型" },
            { english: "all sorts of", chinese: "各种各样的" },
            { english: "independently", chinese: "独立地，自立地" },
            { english: "power", chinese: "电，电力；力量" },
            { english: "supply", chinese: "供应，供给" },
            { english: "unstable", chinese: "不稳定的" },
            { english: "dusty", chinese: "布满灰尘的" },
            { english: "muddy", chinese: "泥泞的，多泥的" },
            { english: "tough", chinese: "困难的，难办的" },
            { english: "flash", chinese: "闪现，闪过；照相机闪光灯" },
            { english: "give up", chinese: "放弃" },
            { english: "deal with", chinese: "对付，应付，处理" },
            { english: "responsible", chinese: "负责的；有责任心的" },
            { english: "be responsible for", chinese: "对……负责" },
            { english: "attractive", chinese: "有吸引力的；好看的，美观的" },
            { english: "as well as", chinese: "……以及……" },
            { english: "laughter", chinese: "笑；笑声" },
            { english: "confident", chinese: "自信的" },
            { english: "*besides", chinese: "除……之外" },
            { english: "contact", chinese: "联系，联络；(写信，打电话) 联系 (某人)" },
            { english: "charity", chinese: "慈善机构，慈善团体" },
            { english: "organisation", chinese: "组织，团体，机构" },
            { english: "contribution", chinese: "贡献" },
            { english: "intend", chinese: "计划，打算，想要" }
        ],
        writingWorkshop: [
            { english: "junior", chinese: "低年级的" },
            { english: "formal", chinese: "正式的，官方的" },
            { english: "informal", chinese: "非正式的" },
            { english: "adapt", chinese: "(使) 适应" },
            { english: "adapt to sth", chinese: "适应某事" },
            { english: "gym", chinese: "体育馆，健身房" },
            { english: "moment", chinese: "某一时刻" },
            { english: "at the moment", chinese: "此刻，目前，眼下" },
            { english: "presentation", chinese: "报告；陈述，说明" },
            { english: "slide", chinese: "幻灯片" },
            { english: "forward", chinese: "向前；进展" },
            { english: "look forward to (doing) sth", chinese: "期待，盼望" }
        ],
        readingClub1: [
            { english: "digestion", chinese: "消化" }
        ],
        readingClub2: [
            { english: "recreation", chinese: "娱乐，消遣" },
            { english: "entertainment", chinese: "娱乐" },
            { english: "rural", chinese: "农村的，乡村的，田园的" }
        ]
    },
    unit2: {
        topicTalk: [
            { english: "athlete", chinese: "运动员" },
            { english: "frequency", chinese: "发生的频率，发生率" },
            { english: "prefer", chinese: "更喜欢" },
            { english: "rather than", chinese: "而不是" },
            { english: "badminton", chinese: "羽毛球" },
            { english: "golf", chinese: "高尔夫" },
            { english: "gymnastics", chinese: "体操" },
            { english: "jog", chinese: "慢跑" },
            { english: "cycle", chinese: "骑自行车" },
            { english: "bowling", chinese: "保龄球" },
            { english: "skateboard", chinese: "滑板；用滑板滑行" },
            { english: "track", chinese: "跑道" },
            { english: "in good / bad shape", chinese: "健康状况良好 / 不佳" },
            { english: "balanced", chinese: "均衡的" },
            { english: "diet", chinese: "日常饮食" },
            { english: "stair", chinese: "楼梯；梯级" },
            { english: "regularly", chinese: "经常；定期地" },
            { english: "net", chinese: "（网球等的）球网；网" },
            { english: "court", chinese: "（网球等的）球场" },
            { english: "within", chinese: "在……之内" }
        ],
        lesson1: [
            { english: "underdog", chinese: "处于劣势的人（队）；弱方" },
            { english: "defeat", chinese: "（在比赛、战争中）战胜，打败" },
            { english: "company", chinese: "公司；一群人" },
            { english: "guy", chinese: "（非正式）男人，家伙" },
            { english: "champion", chinese: "冠军，第一名" },
            { english: "*shot", chinese: "投球，击球；机会" },
            { english: "inspiration", chinese: "激励，鼓舞；给人以灵感的人 / 物；灵感" },
            { english: "try out for sth", chinese: "参加……选拔" },
            { english: "*bench", chinese: "替补队员席" },
            { english: "replacement", chinese: "替换的人（物）" },
            { english: "desire", chinese: "渴望" },
            { english: "crash", chinese: "猛撞" },
            { english: "crash into", chinese: "猛撞，猛击" },
            { english: "gather", chinese: "聚集，聚合" },
            { english: "gather around", chinese: "聚集" },
            { english: "not ... anymore", chinese: "不再……" },
            { english: "pack", chinese: "绷带，敷布；包，包裹；把……包起来" },
            { english: "sharply", chinese: "严厉地，毫不客气地" },
            { english: "let sb down", chinese: "使失望，辜负（别人的信任或期望）" },
            { english: "onto", chinese: "到……上，向……上" },
            { english: "extra", chinese: "额外的，另外的" },
            { english: "pay off", chinese: "取得成功；奏效" },
            { english: "keep up with", chinese: "跟上，保持同步" },
            { english: "energy", chinese: "力量，活力" },
            { english: "crowd", chinese: "人群" },
            { english: "clap", chinese: "鼓掌，拍手" },
            { english: "earn", chinese: "赢得；博得" }
        ],
        lesson2: [
            { english: "boxing", chinese: "拳击（运动）" },
            { english: "bounce", chinese: "（使）弹起，（使）反弹" },
            { english: "belt", chinese: "腰带，皮带" },
            { english: "announcement", chinese: "通告，公告" },
            { english: "defence", chinese: "防守队员，后卫" },
            { english: "audience", chinese: "观众；听众" },
            { english: "remind", chinese: "使（某人）想起，提醒" },
            { english: "bite", chinese: "咬" },
            { english: "prohibit", chinese: "禁止" },
            { english: "case", chinese: "状况，场合；事例，实例" },
            { english: "in case", chinese: "以防万一" },
            { english: "sign up", chinese: "报名" },
            { english: "annual", chinese: "一年一度的，每年的" },
            { english: "application", chinese: "申请书" },
            { english: "warm-up", chinese: "热身运动，准备活动" },
            { english: "quit", chinese: "停止（做某事）" },
            { english: "halfway", chinese: "半途地" },
            { english: "tip", chinese: "建议，忠告，窍门" },
            { english: "ought to", chinese: "应该，应当" },
            { english: "occupy", chinese: "占用，占去（时间）" },
            { english: "disappointment", chinese: "失望；扫兴；沮丧" },
            { english: "amazingly", chinese: "惊人地，了不起地" }
        ],
        lesson3: [
            { english: "relieve", chinese: "减轻，缓解" },
            { english: "strengthen", chinese: "（使）强健" },
            { english: "*immune", chinese: "免疫的；有免疫力的" },
            { english: "system", chinese: "系统" },
            { english: "immune system", chinese: "免疫系统" },
            { english: "cheer up", chinese: "（使）高兴起来，（使）振作起来" },
            { english: "weekly", chinese: "一周一次的，每周的" },
            { english: "be fed up with", chinese: "厌烦的，不满的，无法再忍受的" },
            { english: "awkward", chinese: "令人尴尬的" },
            { english: "particular", chinese: "尤其，特别；特定的" },
            { english: "in particular", chinese: "尤其，特别" },
            { english: "benefit", chinese: "好处，益处" },
            { english: "membership", chinese: "会员身份" },
            { english: "equipment", chinese: "设备，装备" },
            { english: "capable", chinese: "能干的；能力强的" },
            { english: "be capable of", chinese: "有能力做" },
            { english: "prevent", chinese: "预防；阻止，阻挡" },
            { english: "disease", chinese: "疾病" },
            { english: "upper", chinese: "较上的，上面的" },
            { english: "flow", chinese: "流，流动；流动" },
            { english: "oxygen", chinese: "氧" },
            { english: "relief", chinese: "减轻，缓解" },
            { english: "ache", chinese: "隐痛" },
            { english: "guideline", chinese: "指导方针，指导原则" },
            { english: "click", chinese: "点击（鼠标）" },
            { english: "detail", chinese: "细节" },
            { english: "principle", chinese: "原则，基本的观念" },
            { english: "amount", chinese: "数量，数额" },
            { english: "shortcut", chinese: "捷径，近路" },
            { english: "overnight", chinese: "突然，一下子" },
            { english: "achievable", chinese: "可完成的；做得成的" },
            { english: "make sure", chinese: "确保" },
            { english: "muscle", chinese: "肌肉" },
            { english: "bone", chinese: "骨头，骨" },
            { english: "satisfaction", chinese: "满足，满意" },
            { english: "sweat", chinese: "汗水" },
            { english: "overdo", chinese: "把……做得过火" }
        ],
        writingWorkshop: [
            { english: "sight", chinese: "视野" },
            { english: "cyclist", chinese: "骑自行车者，自行车运动员" },
            { english: "overtake", chinese: "超过" },
            { english: "amazed", chinese: "大为惊奇的，惊讶的" },
            { english: "sportsmanship", chinese: "体育精神" },
            { english: "*bronze", chinese: "铜" },
            { english: "medal", chinese: "奖牌；勋章" },
            { english: "response", chinese: "回答，答复" },
            { english: "*gesture", chinese: "姿态；手势；姿势" },
            { english: "take advantage of sth", chinese: "利用某物" }
        ],
        readingClub1: [
            { english: "defend", chinese: "保护，保卫" }
        ],
        readingClub2: [
            { english: "flexibility", chinese: "灵活性" }
        ]
    },
    unit3: {
        topicTalk: [
            { english: "occasion", chinese: "重要的社交活动；时刻，时候" },
            { english: "dragon", chinese: "龙" },
            { english: "Dragon-Boat Festival", chinese: "端午节" },
            { english: "graduation", chinese: "毕业" },
            { english: "lunar", chinese: "阴历的；月球的" },
            { english: "lunar month", chinese: "阴历月，农历月" },
            { english: "barbecue", chinese: "烧烤野餐" },
            { english: "sticky", chinese: "黏性的，黏的" },
            { english: "adult", chinese: "成人，成年人" },
            { english: "lantern", chinese: "灯笼，提灯" },
            { english: "turkey", chinese: "火鸡" },
            { english: "congratulation", chinese: "恭喜，祝贺" },
            { english: "decorate", chinese: "装饰，布置，美化" },
            { english: "tradition", chinese: "传统" },
            { english: "*monster", chinese: "怪兽，怪物" }
        ],
        lesson1: [
            { english: "immediately", chinese: "即刻，马上" },
            { english: "gathering", chinese: "聚会" },
            { english: "snack", chinese: "（正餐以外的）小吃，点心" },
            { english: "put up", chinese: "张贴" },
            { english: "decoration", chinese: "装饰物" },
            { english: "let off", chinese: "使某物爆炸" },
            { english: "account", chinese: "描述，报道" },
            { english: "summarise", chinese: "总结，概括" },
            { english: "host", chinese: "主人；东道主；主持人" },
            { english: "sweep", chinese: "扫；打扫" },
            { english: "sweep away", chinese: "扫除；清除" },
            { english: "character", chinese: "字，字体；人物，角色" },
            { english: "attach", chinese: "贴；固定；附上" },
            { english: "upside down", chinese: "倒置地，颠倒地" },
            { english: "expectant", chinese: "期待的，期望的" },
            { english: "scare", chinese: "吓唬；使（某人）惊恐" },
            { english: "scare sb / sth away", chinese: "把……吓跑" },
            { english: "flight", chinese: "航班" },
            { english: "wine", chinese: "葡萄酒" },
            { english: "surround", chinese: "环绕，围绕" },
            { english: "accent", chinese: "口音" },
            { english: "hotpot", chinese: "火锅" },
            { english: "*firecracker", chinese: "鞭炮，爆竹" },
            { english: "retired", chinese: "退休的" },
            { english: "*buzz", chinese: "闹哄哄，喧闹" },
            { english: "joy", chinese: "欢欣，愉快，喜悦" },
            { english: "throughout", chinese: "在整个期间，自始至终" },
            { english: "original", chinese: "原先的，最早的，最初的" },
            { english: "custom", chinese: "风俗，习惯；传统" }
        ],
        lesson2: [
            { english: "wedding", chinese: "婚礼" },
            { english: "greet", chinese: "问候，欢迎；打招呼" },
            { english: "beer", chinese: "啤酒" },
            { english: "teenager", chinese: "青少年，十几岁的孩子" },
            { english: "studio", chinese: "录音室" },
            { english: "as far as", chinese: "就……而言" },
            { english: "appropriately", chinese: "合适地，适当地" },
            { english: "specific", chinese: "具体的，特定的" },
            { english: "neat", chinese: "整洁的" },
            { english: "suit", chinese: "套装" },
            { english: "jeans", chinese: "牛仔裤" },
            { english: "in general", chinese: "普遍地" },
            { english: "pudding", chinese: "布丁；甜食，甜点心" },
            { english: "effort", chinese: "努力；力气" },
            { english: "make an effort", chinese: "尽力" },
            { english: "represent", chinese: "代表" },
            { english: "extend", chinese: "提供，给予，表示" },
            { english: "fortunate", chinese: "幸运的" }
        ],
        lesson3: [
            { english: "memory", chinese: "记忆，回忆" },
            { english: "*stocking", chinese: "长筒袜" },
            { english: "move in", chinese: "搬来（和某人）一起居住" },
            { english: "somehow", chinese: "不知怎的；不知为什么" },
            { english: "slightly", chinese: "略微，稍微" },
            { english: "pole", chinese: "地极，北 / 南极" },
            { english: "envelope", chinese: "信封" },
            { english: "stuff", chinese: "给……填馅；填，塞" },
            { english: "lap", chinese: "大腿部" },
            { english: "frosty", chinese: "严寒的" },
            { english: "patience", chinese: "耐心；耐力" },
            { english: "over and over", chinese: "再三地，重复地" },
            { english: "eve", chinese: "前夕；前一天" },
            { english: "branch", chinese: "树枝" },
            { english: "plate", chinese: "盘；碟" },
            { english: "behaviour", chinese: "行为，举止" },
            { english: "whisper", chinese: "低声说，低语" },
            { english: "merry", chinese: "快乐的" },
            { english: "ballet", chinese: "芭蕾舞剧，芭蕾舞表演" },
            { english: "roll", chinese: "使成筒形（球形）；一卷；面包卷" },
            { english: "catch sb's eye", chinese: "吸引某人的目光；引起某人的注意" },
            { english: "wave", chinese: "挥手；招手" },
            { english: "affair", chinese: "事件" },
            { english: "*swallow", chinese: "吞下，咽下" },
            { english: "pass away", chinese: "去世" },
            { english: "no longer", chinese: "不再" }
        ],
        writingWorkshop: [
            { english: "event", chinese: "事件；活动" },
            { english: "description", chinese: "描述，描写" },
            { english: "awesome", chinese: "令人赞叹的；很好的" },
            { english: "downstairs", chinese: "往楼下，在楼下" },
            { english: "nowhere", chinese: "哪里都不" },
            { english: "select", chinese: "挑选，选拔" },
            { english: "*album", chinese: "簿，册" },
            { english: "calm", chinese: "（使）平静，（使）镇定" },
            { english: "calm down", chinese: "冷静下来" },
            { english: "uniform", chinese: "制服" },
            { english: "tear", chinese: "眼泪，泪水" }
        ],
        readingClub1: [
            { english: "cuisine", chinese: "烹饪" }
        ],
        readingClub2: [
            { english: "thoroughly", chinese: "完全地" },
            { english: "humbly", chinese: "谦虚地" }
        ]
    }
};

// 调试用：检查数据加载
console.log("单词库加载完成，共", Object.keys(wordData).length, "个单元");

// 确保wordData已全局可用
if (typeof window !== 'undefined') {
    window.wordData = wordData;
}