// words.js - 高二必修单词库
const wordData = {
    unit4: {
        topicTalk: [
            { english: "app", chinese: "应用程序" },
            { english: "enable", chinese: "使可能，使发生" },
            { english: "convenience", chinese: "方便，便利" },
            { english: "effect", chinese: "效应；影响" },
            { english: "impact", chinese: "影响；作用" },
            { english: "self - focused", chinese: "以自我为中心的；关注自我的" },
            { english: "addicted", chinese: "对……着迷的；沉迷的" },
            { english: "be addicted to", chinese: "沉迷" },
            { english: "indeed", chinese: "确实；当然" },
            { english: "download", chinese: "下载" },
            { english: "recommendation", chinese: "建议，提议；推荐" },
            { english: "super", chinese: "极好的，了不起的" },
            { english: "*avatar", chinese: "（网络上代表个人的）头像，虚拟替身，图标" },
            { english: "explore", chinese: "探究；探讨；探险" },
            { english: "personality", chinese: "个性，性格" },
            { english: "admit", chinese: "承认" },
            { english: "alarm", chinese: "闹钟" }
        ],
        lesson1: [
            { english: "image", chinese: "图像；形象" },
            { english: "fancy", chinese: "花哨的；别致的" },
            { english: "trick", chinese: "欺骗，诱骗，哄骗" },
            { english: "identity", chinese: "身份；特征" },
            { english: "2D", chinese: "二维的" },
            { english: "variety", chinese: "多样化，变化" },
            { english: "a variety of", chinese: "各种各样的" },
            { english: "sex", chinese: "性别" },
            { english: "sensible", chinese: "朴素实用的；明智的，合理的" },
            { english: "creativity", chinese: "创造力；独创性" },
            { english: "blog", chinese: "博客；网络日志（写博客 ）" },
            { english: "obviously", chinese: "显而易见地，明显地" },
            { english: "experiment", chinese: "做试验，进行实验；实验" },
            { english: "hairstyle", chinese: "发型，发式" },
            { english: "nowadays", chinese: "现今，现时" },
            { english: "selection", chinese: "供选择的同类物品；选择" },
            { english: "type", chinese: "打；打字；类型，种类" },
            { english: "concern", chinese: "担忧，忧虑；与……有关；使担心" },
            { english: "virtual", chinese: "虚拟的；模拟的" },
            { english: "cheat", chinese: "欺骗；欺诈" },
            { english: "view", chinese: "看，把……视为" }
        ],
        lesson2: [
            { english: "accommodation", chinese: "住处" },
            { english: "subscribe", chinese: "订阅，订购" },
            { english: "powerful", chinese: "效能高的；强有力的；强壮的" },
            { english: "latest", chinese: "最新的；最近的" },
            { english: "reality", chinese: "现实；真实" },
            { english: "VR (Virtual Reality)", chinese: "虚拟现实" },
            { english: "AR (Augmented Reality)", chinese: "增强现实" },
            { english: "MR (Mixed Reality)", chinese: "混合现实" },
            { english: "account", chinese: "账户" },
            { english: "software", chinese: "计算机软件" },
            { english: "device", chinese: "设备，装置" },
            { english: "mobile device", chinese: "移动设备" },
            { english: "ensure", chinese: "确保，保证" },
            { english: "material", chinese: "材料；素材" },
            { english: "press", chinese: "按" },
            { english: "button", chinese: "按钮" },
            { english: "gender", chinese: "性别" },
            { english: "goods", chinese: "商品" },
            { english: "favour", chinese: "恩惠；善意的行为" },
            { english: "confirm", chinese: "确认；证实" },
            { english: "deliver", chinese: "递送；传送" },
            { english: "error", chinese: "错误；失误" }
        ],
        lesson3: [
            { english: "harm", chinese: "伤害，损害" },
            { english: "argument", chinese: "论点；论据" },
            { english: "replace", chinese: "取代；接替" },
            { english: "hug", chinese: "拥抱；紧抱" },
            { english: "concentrate", chinese: "专注，专心；集中注意力" },
            { english: "concerned", chinese: "关切的，关心的" },
            { english: "be concerned with", chinese: "关心……" },
            { english: "rewarding", chinese: "有益的；有意义的" },
            { english: "addition", chinese: "增添；添加" },
            { english: "in addition", chinese: "除此之外" },
            { english: "content", chinese: "内容" },
            { english: "shallow", chinese: "肤浅的，浅薄的" },
            { english: "*trivial", chinese: "没有什么价值的；微不足道的" },
            { english: "basis", chinese: "基础；基点" },
            { english: "percent", chinese: "百分比；百分数" },
            { english: "opinion", chinese: "意见；看法；主张" },
            { english: "focus", chinese: "集中（注意力）；焦点" },
            { english: "focus on", chinese: "关注" },
            { english: "maintain", chinese: "保持；维持" },
            { english: "smartphone", chinese: "智能手机" },
            { english: "tablet", chinese: "平板电脑；药片；碑，牌" },
            { english: "limiting", chinese: "局限的，限制性的" },
            { english: "brief", chinese: "简洁的，简明的" },
            { english: "*emoji", chinese: "表情符号" },
            { english: "creative", chinese: "创造性的" },
            { english: "*thought - provoking", chinese: "发人深省的，令人深思的" },
            { english: "authority", chinese: "权威人士；专家" }
        ],
        writingWorkshop: [
            { english: "profile", chinese: "人物简介；传略" },
            { english: "location", chinese: "位置；地点" },
            { english: "optional", chinese: "可选择的；非强制的" },
            { english: "imaginary", chinese: "想象的，虚构的" },
            { english: "fantasy", chinese: "幻想作品" },
            { english: "series", chinese: "系列" },
            { english: "author", chinese: "作者，作家" },
            { english: "amazing", chinese: "了不起的；惊人的" },
            { english: "privacy", chinese: "隐私" },
            { english: "policy", chinese: "政策，方针" }
        ],
        readingClub1: [
            { english: "digitise", chinese: "把……转变成数字形式，使……数字化" },
            { english: "sailor", chinese: "水手，海员" },
            { english: "accessible", chinese: "易懂的；易得到的" }
        ],
        readingClub2: [
            { english: "wristband", chinese: "腕带" }
        ]
    },
    unit5: {
        topicTalk: [
            { english: "disaster", chinese: "灾难；灾祸" },
            { english: "flood", chinese: "洪水，水灾" },
            { english: "drought", chinese: "旱灾，干旱" },
            { english: "hurricane", chinese: "飓风" },
            { english: "landslide", chinese: "滑坡；塌方" },
            { english: "volcanic", chinese: "火山的；由火山作用引起的" },
            { english: "eruption", chinese: "爆发" },
            { english: "wildlife", chinese: "野生动植物，野生生物" },
            { english: "comment", chinese: "评论；意见" },
            { english: "crowded", chinese: "拥挤的；挤满人的" },
            { english: "landscape", chinese: "风景，景色" },
            { english: "living", chinese: "活的，活着的" },
            { english: "weed", chinese: "野草；海藻" },
            { english: "deer", chinese: "鹿" },
            { english: "insect", chinese: "昆虫" },
            { english: "whale", chinese: "鲸" },
            { english: "dolphin", chinese: "海豚" },
            { english: "shark", chinese: "鲨（鱼）" },
            { english: "kangaroo", chinese: "袋鼠" },
            { english: "eagle", chinese: "鹰" },
            { english: "fox", chinese: "狐狸" },
            { english: "soil", chinese: "土壤" },
            { english: "climate", chinese: "气候" },
            { english: "ecology", chinese: "生态；生态学" },
            { english: "jungle", chinese: "（热带）丛林" },
            { english: "shock", chinese: "使震惊；使难以置信" },
            { english: "lecture", chinese: "讲座，讲课；演讲" },
            { english: "overuse", chinese: "过度使用；滥用" },
            { english: "million", chinese: "百万" },
            { english: "greenhouse", chinese: "温室，暖房" },
            { english: "turn one's back (on sb / sth)", chinese: "对……置之不理，对……撒手不管" },
            { english: "title", chinese: "题目，标题" }
        ],
        lesson1: [
            { english: "*whirlpool", chinese: "漩涡" },
            { english: "wave", chinese: "海浪；波涛" },
            { english: "escape", chinese: "逃离；逃避" },
            { english: "survive", chinese: "活下来；幸存" },
            { english: "*float", chinese: "浮；漂" },
            { english: "file", chinese: "档案，卷宗" },
            { english: "*descent", chinese: "下降，下落" },
            { english: "*tidal", chinese: "潮汐的，潮水的" },
            { english: "poetry", chinese: "诗歌；作诗的艺术" },
            { english: "*mystery", chinese: "神秘事物，难以理解的事物" },
            { english: "soul", chinese: "灵魂" },
            { english: "frightened", chinese: "受惊的，害怕的" },
            { english: "horrible", chinese: "可怕的，吓人的，令人恐惧的" },
            { english: "edge", chinese: "边缘" },
            { english: "on the edge of", chinese: "在……边缘；某事快要发生（尤指不好的事 ）" },
            { english: "*barrel", chinese: "桶" },
            { english: "curious", chinese: "好奇的" },
            { english: "observation", chinese: "观察；观察结果" },
            { english: "equal", chinese: "相等的；相同的" },
            { english: "extent", chinese: "面积；长度；范围；程度" },
            { english: "tube", chinese: "圆管，管子；（伦敦）地铁" }
        ],
        lesson2: [
            { english: "rescue", chinese: "营救；救援" },
            { english: "vehicle", chinese: "交通工具，车辆" },
            { english: "trap", chinese: "困住；使陷于危险中" },
            { english: "attempt", chinese: "努力，尝试，企图" },
            { english: "interrupt", chinese: "打断讲话" },
            { english: "death", chinese: "死，死亡" },
            { english: "loss", chinese: "丧失；死亡" },
            { english: "damage", chinese: "伤害，损伤，损害" },
            { english: "measure", chinese: "估量，衡量；测量" },
            { english: "operation", chinese: "行动，活动；手术；操作" },
            { english: "overseas", chinese: "在海外，在外国" },
            { english: "site", chinese: "场所，地点" },
            { english: "process", chinese: "过程，进程" },
            { english: "battle", chinese: "较量，竞争；斗争；战斗" },
            { english: "duty", chinese: "职责，义务；责任" },
            { english: "suffering", chinese: "（肉体或精神上的）痛苦；折磨" },
            { english: "conduct", chinese: "实施；进行；执行；指挥" },
            { english: "protection", chinese: "保护；防护" },
            { english: "lamp", chinese: "灯" },
            { english: "nearby", chinese: "附近" },
            { english: "breathe", chinese: "呼吸" },
            { english: "breathe in", chinese: "吸气" },
            { english: "dust", chinese: "灰尘；尘埃" },
            { english: "run out", chinese: "用完；耗尽" }
        ],
        lesson3: [
            { english: "explorer", chinese: "探险者；勘察者" },
            { english: "preparation", chinese: "预备，准备" },
            { english: "*sledge", chinese: "雪橇" },
            { english: "ski", chinese: "滑雪板；滑雪" },
            { english: "captain", chinese: "上校；队长；组长" },
            { english: "polar", chinese: "极地的，地极的" },
            { english: "base", chinese: "基地，大本营；基础；以……为基地" },
            { english: "anxiously", chinese: "焦虑地；不安地" },
            { english: "break down", chinese: "停止运转，出故障" },
            { english: "ambition", chinese: "抱负，雄心；追求，夙愿" },
            { english: "solid", chinese: "连续的，不间断的；固体的，坚硬的" },
            { english: "exploration", chinese: "探险；探索" },
            { english: "cheerful", chinese: "高兴的，兴高采烈的" },
            { english: "*gear", chinese: "成套服装" },
            { english: "prove", chinese: "证明；证实" },
            { english: "distant", chinese: "久远的；遥远的" },
            { english: "continent", chinese: "洲，大洲；大陆" },
            { english: "*dissuade", chinese: "劝阻" },
            { english: "*tent", chinese: "帐篷" },
            { english: "tale", chinese: "故事" },
            { english: "honesty", chinese: "坦诚；诚实，正直" },
            { english: "sincerity", chinese: "真诚，真挚，诚实" },
            { english: "bravery", chinese: "勇气；勇敢的行为" }
        ],
        writingWorkshop: [
            { english: "brochure", chinese: "小册子" },
            { english: "shelter", chinese: "避难所" },
            { english: "aftershock", chinese: "（地震的）余震" },
            { english: "observe", chinese: "观察；注意" },
            { english: "metal", chinese: "金属" }
        ],
        readingClub1: [
            { english: "varied", chinese: "各种各样的，形形色色的" },
            { english: "scary", chinese: "可怕的，恐怖的" },
            { english: "harmless", chinese: "无害的" },
            { english: "skiing", chinese: "滑雪运动" }
        ],
        readingClub2: [
            { english: "originality", chinese: "独创性；创造力" },
            { english: "disappearance", chinese: "消亡；消失" }
        ]
    },
    unit6: {
        topicTalk: [
            { english: "admirable", chinese: "令人钦佩的；极其出色的" },
            { english: "admire", chinese: "钦佩；欣赏" },
            { english: "career", chinese: "职业，事业" },
            { english: "put out fires", chinese: "灭火" },
            { english: "cure", chinese: "治好（疾病）；治愈；疗法" },
            { english: "fight for...", chinese: "努力争取，为……斗争" },
            { english: "justice", chinese: "公平，公正" },
            { english: "generation", chinese: "一代（人）" },
            { english: "reform", chinese: "改革；改进" },
            { english: "remarkable", chinese: "不寻常的；显著的；非凡的" },
            { english: "mankind", chinese: "人类" },
            { english: "intelligent", chinese: "聪敏的；有智慧的" },
            { english: "generous", chinese: "无私的；慷慨的；大方的" },
            { english: "have... in mind", chinese: "心里已有……" },
            { english: "*evil", chinese: "邪恶之事；祸害；邪恶的" },
            { english: "creatively", chinese: "创造性地；有创造力地" }
        ],
        lesson1: [
            { english: "mosquito", chinese: "蚊子" },
            { english: "apart", chinese: "分开；散开；除……之外" },
            { english: "drug", chinese: "药物，药材；毒品" },
            { english: "effective", chinese: "有效的，产生预期效果的" },
            { english: "female", chinese: "女（性）的" },
            { english: "stage", chinese: "舞台；阶段" },
            { english: "award", chinese: "授予；给予" },
            { english: "committee", chinese: "委员会" },
            { english: "honour", chinese: "荣誉；感到荣幸" },
            { english: "recognition", chinese: "表彰；赞扬" },
            { english: "academy", chinese: "研究院；学会" },
            { english: "gain", chinese: "获得，赢得，取得；受益；好处；利益" },
            { english: "establish", chinese: "建立，设立" },
            { english: "chemical", chinese: "化学品；化学的" },
            { english: "herb", chinese: "药草" },
            { english: "literature", chinese: "文献资料；著述；文学" },
            { english: "recipe", chinese: "处方；秘诀" },
            { english: "limited", chinese: "有限的" },
            { english: "resource", chinese: "物力；资源" },
            { english: "staff", chinese: "全体职员，员工" },
            { english: "eventually", chinese: "最终；终于" },
            { english: "come across", chinese: "偶然发现；偶遇" },
            { english: "promising", chinese: "大有希望的" },
            { english: "*fame", chinese: "名声，名誉" },
            { english: "*renowned", chinese: "著名的，有名望的" },
            { english: "despite", chinese: "尽管；虽然" },
            { english: "wisdom", chinese: "知识，学问；智慧" },
            { english: "potential", chinese: "潜力；可能性" },
            { english: "advance", chinese: "发展；进步" },
            { english: "integrate", chinese: "（使）结合；（使）成为一体" }
        ],
        lesson2: [
            { english: "pick out", chinese: "挑选" },
            { english: "independence", chinese: "独立" },
            { english: "peaceful", chinese: "和平的，没有暴力的" },
            { english: "protest", chinese: "抗议；反对" },
            { english: "racial", chinese: "种族的；人种的" },
            { english: "discrimination", chinese: "歧视" },
            { english: "inspiring", chinese: "鼓舞人心的" },
            { english: "bar", chinese: "铁栅；（门、窗等的）闩" },
            { english: "behind bars", chinese: "在牢里" },
            { english: "skin", chinese: "皮肤" },
            { english: "What a shame!", chinese: "真遗憾！" },
            { english: "further", chinese: "更多的，进一步" },
            { english: "march", chinese: "示威游行，抗议游行" },
            { english: "self-evident", chinese: "不证自明的；显而易见的" },
            { english: "judge", chinese: "评价；判断" },
            { english: "impressive", chinese: "令人钦佩的，给人印象深刻的" },
            { english: "respect", chinese: "尊敬；敬佩" },
            { english: "independent", chinese: "独立的，自主的" },
            { english: "the other day", chinese: "不久前某一天" }
        ],
        lesson3: [
            { english: "*horror", chinese: "令人惊恐的事" },
            { english: "regard", chinese: "认为，看作" },
            { english: "be regarded as", chinese: "被认为，被看作" },
            { english: "novelist", chinese: "小说家" },
            { english: "journalist", chinese: "新闻工作者" },
            { english: "passion", chinese: "强烈的爱好，热爱；激情" },
            { english: "opportunity", chinese: "机会；时机" },
            { english: "reputation", chinese: "名誉；名望" },
            { english: "awareness", chinese: "认识；意识" },
            { english: "organisation", chinese: "组织；团体；机构" },
            { english: "strike", chinese: "突然发生（某种不幸）；突然有坏的影响；打，击" },
            { english: "severe", chinese: "很严重的" },
            { english: "movement", chinese: "运动，动作，活动" },
            { english: "*nightmare", chinese: "噩梦，梦魇" },
            { english: "depression", chinese: "忧郁，沮丧，消沉；抑郁症" },
            { english: "due to", chinese: "由于，因为" },
            { english: "ongoing", chinese: "继续进行的，不断发展的" },
            { english: "commitment", chinese: "投入，忠诚，奉献；承诺" },
            { english: "*undertake", chinese: "着手做，承担" },
            { english: "intense", chinese: "强烈的，剧烈的" },
            { english: "engage", chinese: "参加，参与" },
            { english: "design", chinese: "计划，设计" },
            { english: "*biography", chinese: "传记" },
            { english: "passionate", chinese: "具有强烈信念的；热爱的，酷爱的" },
            { english: "energetic", chinese: "精力充沛的，充满活力的" },
            { english: "advocate", chinese: "提倡者；拥护者；鼓吹者" },
            { english: "disability", chinese: "伤残，残障，障碍" },
            { english: "attitude", chinese: "看法，态度" }
        ],
        writingWorkshop: [
            { english: "summary", chinese: "概要；摘要；总结" }
        ],
        readingClub1: [
            { english: "daring", chinese: "勇敢的" }
        ],
        readingClub2: [
            { english: "originally", chinese: "原先，最初" },
            { english: "in spite of", chinese: "尽管……（仍……）；虽然；不顾" }
        ]
    }
};

// 调试用：检查数据加载
console.log("单词库加载完成，共", Object.keys(wordData).length, "个单元");

// 确保wordData已全局可用
if (typeof window !== 'undefined') {
    window.wordData = wordData;
}
