// word.js - 高三必修单词库
const wordData = {
    unit7: {
        topicTalk: [
            { english: "opera", chinese: "歌剧；歌剧艺术" },
            { english: "band", chinese: "乐队；乐团" },
            { english: "performance", chinese: "表演；演出" },
            { english: "exhibition", chinese: "展出（会），展览" },
            { english: "classical", chinese: "（音乐）古典的；传统的" },
            { english: "jazz", chinese: "爵士乐" },
            { english: "drama", chinese: "戏剧" },
            { english: "comedy", chinese: "喜剧片；喜剧节目" },
            { english: "calligraphy", chinese: "书法" },
            { english: "performer", chinese: "表演者；演奏者；演员" },
            { english: "talented", chinese: "有才能的；有天资的" },
            { english: "component", chinese: "组成部分" },
            { english: "costume", chinese: "戏装；化装服" },
            { english: "shade", chinese: "（画的）阴影部分" },
            { english: "atmosphere", chinese: "气氛；氛围" },
            { english: "monthly", chinese: "每月；每月一次地" },
            { english: "uplifting", chinese: "令人振奋的" }
        ],
        lesson1: [
            { english: "masterpiece", chinese: "杰作；代表作" },
            { english: "figure", chinese: "人像，人形；数字" },
            { english: "starry", chinese: "布满星星的" },
            { english: "mentally", chinese: "精神上；心理上" },
            { english: "massive", chinese: "巨大的" },
            { english: "beneath", chinese: "在……（正）下方" },
            { english: "affect", chinese: "影响" },
            { english: "spot", chinese: "（圆）点；斑点；污渍" },
            { english: "failure", chinese: "失败的事；失败" },
            { english: "scream", chinese: "尖叫，尖叫声；高声喊出" },
            { english: "striking", chinese: "惊人的；显著的" },
            { english: "let out a scream", chinese: "发出尖叫声" },
            { english: "viewer", chinese: "观看者" },
            { english: "burning", chinese: "燃烧着的" },
            { english: "cause", chinese: "导致，引起；使发生；原因；事业" },
            { english: "*empire", chinese: "帝国；大企业" },
            { english: "scene", chinese: "景色" },
            { english: "*mysterious", chinese: "神秘的；难以解释的" },
            { english: "visual", chinese: "视觉的，视力的" },
            { english: "reaction", chinese: "反应" }
        ],
        lesson2: [
            { english: "male", chinese: "男（性）的" },
            { english: "*mask", chinese: "面具" },
            { english: "*clown", chinese: "小丑" },
            { english: "emotion", chinese: "情感" },
            { english: "*acrobatic", chinese: "杂技" },
            { english: "master", chinese: "掌握，精通；大师；主人" },
            { english: "refer", chinese: "提到；谈到" },
            { english: "refer to", chinese: "提到" },
            { english: "perform", chinese: "表演；演出" },
            { english: "pattern", chinese: "图案；花样，式样" },
            { english: "otherwise", chinese: "否则；要不然" },
            { english: "*carriage", chinese: "马车" },
            { english: "complex", chinese: "复杂的" },
            { english: "aspect", chinese: "方面" }
        ],
        lesson3: [
            { english: "*orchestra", chinese: "（大型的）管弦乐队" },
            { english: "genius", chinese: "天才" },
            { english: "*symphony", chinese: "交响乐，交响曲" },
            { english: "minor", chinese: "（音乐）小调的；小的；不很重要的" },
            { english: "composer", chinese: "作曲家" },
            { english: "piano", chinese: "钢琴" },
            { english: "struggle", chinese: "奋斗；拼搏" },
            { english: "proceed", chinese: "继续进行" },
            { english: "note", chinese: "单音，音调，音符" },
            { english: "score", chinese: "乐谱；比分；成绩" },
            { english: "respond", chinese: "回应，回复" },
            { english: "backstage", chinese: "后台的" },
            { english: "tense", chinese: "紧张的；焦虑不安的" },
            { english: "conductor", chinese: "指挥" },
            { english: "hesitate", chinese: "犹豫；踌躇" },
            { english: "not hesitate to do sth", chinese: "毫不犹豫做某事，尽管做某事" },
            { english: "charge", chinese: "主管；负责" },
            { english: "take charge of", chinese: "负责" },
            { english: "joyous", chinese: "欢乐的，令人愉快的" },
            { english: "signal", chinese: "标志着；预示；标识" },
            { english: "broad", chinese: "宽阔的；广博的" },
            { english: "broad smile", chinese: "满面的笑容" },
            { english: "compose", chinese: "作（曲）；构成；写作" }
        ],
        writingWorkshop: [
            { english: "advertisement", chinese: "广告" },
            { english: "youth", chinese: "（青）少年" },
            { english: "contest", chinese: "比赛，竞赛" },
            { english: "*martial", chinese: "军事的；战争的" },
            { english: "martial arts", chinese: "武术" },
            { english: "madam", chinese: "女士；夫人" },
            { english: "documentary", chinese: "纪录片" },
            { english: "currently", chinese: "当前；现时" },
            { english: "acceptable", chinese: "可接受的" },
            { english: "individual", chinese: "个人，个体" },
            { english: "appreciate", chinese: "感激；欣赏" },
            { english: "faithfully", chinese: "忠诚地，忠实地" }
        ],
        readingClub1: [
            { english: "expressive", chinese: "富于感情的；明确表露想法的" },
            { english: "artistic", chinese: "美术的；艺术的" },
            { english: "extensively", chinese: "广泛地；大规模地；全面地" },
            { english: "symbolism", chinese: "象征主义" },
            { english: "sculptor", chinese: "雕刻家" },
            { english: "admiration", chinese: "敬佩；羡慕" },
            { english: "best - selling", chinese: "畅销的" }
        ],
        readingClub2: [
            { english: "permission", chinese: "允许；许可" },
            { english: "threatening", chinese: "（行为）带有威胁的" },
            { english: "messy", chinese: "脏的；凌乱的" },
            { english: "punishable", chinese: "可依法惩处的" }
        ]
    },
    unit8: {
        topicTalk: [
            { english: "*tap", chinese: "龙头；阀门" },
            { english: "tissue", chinese: "纸巾" },
            { english: "ocean", chinese: "海洋，大海" },
            { english: "smog", chinese: "雾霾" },
            { english: "desert", chinese: "沙漠" },
            { english: "global", chinese: "全球的，全世界的" },
            { english: "industrial", chinese: "工业的" },
            { english: "extinction", chinese: "灭绝" },
            { english: "solution", chinese: "解决办法" },
            { english: "electricity", chinese: "电" },
            { english: "transport", chinese: "交通运输系统，运输方式" },
            { english: "recycle", chinese: "再利用，回收利用" },
            { english: "battery", chinese: "电池" },
            { english: "carbon", chinese: "碳" },
            { english: "balance", chinese: "平衡" },
            { english: "do my part for sth", chinese: "尽自己所能做某事" },
            { english: "flat", chinese: "一套公寓房，一套住房；平坦的" }
        ],
        lesson1: [
            { english: "root", chinese: "树根" },
            { english: "shoot", chinese: "芽，苗；嫩枝；射中；射击" },
            { english: "bother", chinese: "费心，麻烦" },
            { english: "can't be bothered to do sth", chinese: "懒得做某事" },
            { english: "*just-me-ism", chinese: "以自我为中心，自我中心主义" },
            { english: "*gallon", chinese: "加仑" },
            { english: "take action", chinese: "采取行动" },
            { english: "institute", chinese: "机构；研究院" },
            { english: "*chimpanzee", chinese: "黑猩猩" },
            { english: "firm", chinese: "实的；稳固的" },
            { english: "foundation", chinese: "基础；地基" },
            { english: "brick", chinese: "砖，砖块" },
            { english: "all around the world", chinese: "全世界" },
            { english: "*wag", chinese: "（狗）摇（尾巴）" },
            { english: "involve", chinese: "参与；包含" }
        ],
        lesson2: [
            { english: "poster", chinese: "海报" },
            { english: "founder", chinese: "创办人，创始者" },
            { english: "profit", chinese: "盈利，利润" },
            { english: "pm", chinese: "下午" },
            { english: "organiser", chinese: "组织者，安排者" },
            { english: "*union", chinese: "联合会" },
            { english: "contented", chinese: "满意的；满足的" },
            { english: "occur", chinese: "发生" },
            { english: "make sb's dream come true", chinese: "（使）某人梦想成真" },
            { english: "agriculture", chinese: "农业" },
            { english: "proposal", chinese: "建议，提议" },
            { english: "region", chinese: "地区，区域" },
            { english: "slim", chinese: "微小的；苗条的；薄的" },
            { english: "survival", chinese: "继续生存，幸存" },
            { english: "rate", chinese: "比率，率" },
            { english: "quote", chinese: "引文，引用（的话）" },
            { english: "headstone", chinese: "墓碑" },
            { english: "overcome", chinese: "克服（困难）；控制（感情）" },
            { english: "determination", chinese: "决心；毅力" },
            { english: "work through", chinese: "调整（情绪）" },
            { english: "former", chinese: "以前的，从前的" },
            { english: "current", chinese: "当前的，现时的" },
            { english: "county", chinese: "县" },
            { english: "ordinary", chinese: "普通的；平常的" }
        ],
        lesson3: [
            { english: "parking", chinese: "（车辆等的）停放" },
            { english: "therefore", chinese: "因此；由此" },
            { english: "path", chinese: "小径，小道" },
            { english: "come up with", chinese: "想出，想到" },
            { english: "disappear", chinese: "消失，不见" },
            { english: "tracking", chinese: "跟踪" },
            { english: "destination", chinese: "目的地；终点" },
            { english: "*pedal", chinese: "骑；踏板" }
        ],
        writingWorkshop: [
            { english: "resident", chinese: "居民" },
            { english: "official", chinese: "官员，高级职员；公务的；官方的" },
            { english: "attitude", chinese: "看法；态度" },
            { english: "diagram", chinese: "图解，示意图" },
            { english: "percentage", chinese: "百分比，百分率" },
            { english: "take part (in)", chinese: "参加" },
            { english: "cut back on", chinese: "削减，缩减" },
            { english: "*disposable", chinese: "一次性的，用完即丢弃的" },
            { english: "packaging", chinese: "包装盒（瓶、袋），包装材料" },
            { english: "plastic", chinese: "塑料制的" },
            { english: "honey", chinese: "蜂蜜" },
            { english: "butter", chinese: "黄油，牛油" },
            { english: "yoghurt", chinese: "酸奶" },
            { english: "container", chinese: "容器" },
            { english: "majority", chinese: "大多数" },
            { english: "air conditioning", chinese: "空调系统" },
            { english: "sum", chinese: "概括，总结" },
            { english: "to sum up", chinese: "总之" },
            { english: "indicate", chinese: "表明；显示" }
        ],
        readingClub1: [
            { english: "landfill", chinese: "废弃物填埋场" },
            { english: "clean - burning", chinese: "清洁焚烧的" },
            { english: "waste - to - energy", chinese: "以垃圾作为能源的" },
            { english: "footwear", chinese: "鞋类" }
        ],
        readingClub2: [
            { english: "annually", chinese: "每年；一年一度地" },
            { english: "near - surface", chinese: "近地表的" },
            { english: "build - up", chinese: "增长；加强" },
            { english: "pollutant", chinese: "污染物" },
            { english: "flooding", chinese: "水灾，洪水泛滥" },
            { english: "overflow", chinese: "满是，有许多；泛滥" }
        ]
    },
    unit9: {
        topicTalk: [
            { english: "approach", chinese: "方法" },
            { english: "geometry", chinese: "几何（学）" },
            { english: "partner", chinese: "搭档，同伴" },
            { english: "brush up (on)", chinese: "温习，复习" }
        ],
        lesson1: [
            { english: "reflect", chinese: "仔细思考；表达（意见）；反映" },
            { english: "reflect on", chinese: "思考" },
            { english: "argue", chinese: "争论，争吵" },
            { english: "argue with", chinese: "争吵" },
            { english: "assume", chinese: "认为；假定，假设" },
            { english: "automatic", chinese: "自动的；无意识的" },
            { english: "inner", chinese: "内部的" },
            { english: "*outer", chinese: "外部的，外面的" },
            { english: "flexible", chinese: "灵活的，可变通的" },
            { english: "end up doing", chinese: "最后；最终" },
            { english: "promote", chinese: "促进，增进" },
            { english: "work out", chinese: "弄懂某事物；计算出" },
            { english: "in short", chinese: "总而言之；简单地说" },
            { english: "attempt to", chinese: "尝试" },
            { english: "at the heart of...", chinese: "在……的中心" },
            { english: "unlikely", chinese: "不大可能的" },
            { english: "be based on...", chinese: "以……为根据" },
            { english: "dinosaur", chinese: "恐龙" },
            { english: "exist", chinese: "存在；实际上有" },
            { english: "data", chinese: "资料；数据" },
            { english: "ignore", chinese: "忽视；置之不理" },
            { english: "impression", chinese: "印象；感想" }
        ],
        lesson2: [
            { english: "simplified", chinese: "简化了的" },
            { english: "classic", chinese: "经典的" },
            { english: "unfamiliar", chinese: "不熟悉的，不了解的" },
            { english: "memorise", chinese: "记住；熟记" },
            { english: "strategy", chinese: "策略；战略；规划" },
            { english: "effectively", chinese: "有效地" },
            { english: "beyond", chinese: "超出……范围" },
            { english: "recommend", chinese: "推荐；建议" },
            { english: "novel", chinese: "小说" },
            { english: "sufficient", chinese: "充足的" },
            { english: "input", chinese: "输入；投入" },
            { english: "normally", chinese: "通常，平常" },
            { english: "context", chinese: "上下文；语境；背景" },
            { english: "*chunk", chinese: "语块" },
            { english: "acquire", chinese: "学习，获得（知识，技能）" },
            { english: "be honoured to do sth", chinese: "很荣幸做某事" },
            { english: "odd", chinese: "奇特的" },
            { english: "soccer", chinese: "（美）足球" },
            { english: "subway", chinese: "（美）地铁" },
            { english: "in one way or another", chinese: "不管怎样" },
            { english: "worldwide", chinese: "遍及世界的；在全世界" }
        ],
        lesson3: [
            { english: "arrangement", chinese: "计划；安排" },
            { english: "childhood", chinese: "童年，儿童时代" },
            { english: "emotional", chinese: "情感上的；情绪上的" },
            { english: "excitement", chinese: "兴奋，激动" },
            { english: "as a result", chinese: "作为结果" },
            { english: "photographic", chinese: "详细准确的；照片的；摄影的" },
            { english: "digit", chinese: "（0 - 9的任何一个）数字" },
            { english: "*pi (π)", chinese: "圆周率" },
            { english: "*helicopter", chinese: "直升机" },
            { english: "publish", chinese: "出版；发表；刊登" },
            { english: "*curve", chinese: "曲线，弧线" },
            { english: "sharp", chinese: "急剧的，猛烈的；尖的，锋利的" },
            { english: "timely", chinese: "适时的，及时的" },
            { english: "cell", chinese: "细胞" },
            { english: "periodically", chinese: "定期地" },
            { english: "take it easy", chinese: "放轻松" },
            { english: "memorisation", chinese: "记忆" },
            { english: "technique", chinese: "技巧，手法" }
        ],
        writingWorkshop: [
            { english: "reflection", chinese: "沉思；想法；反射" },
            { english: "reflective", chinese: "沉思的；深思的" },
            { english: "journal", chinese: "日记，日志" },
            { english: "moreover", chinese: "此外，而且" }
        ],
        readingClub1: [
            { english: "surfing", chinese: "冲浪" },
            { english: "seafood", chinese: "海鲜" }
        ],
        readingClub2: [
            { english: "gap", chinese: "（大的）差距，差额，差别" },
            { english: "gender", chinese: "性别" },
            { english: "identical", chinese: "完全相同的；非常相似的" },
            { english: "comic", chinese: "连环漫画；滑稽的，好笑的" },
            { english: "fiction", chinese: "小说" },
            { english: "evidence", chinese: "证据，证明" },
            { english: "expose", chinese: "使接触；使体验" },
            { english: "outcome", chinese: "结果，后果" }
        ]
    }
};

// 调试用：检查数据加载
console.log("单词库加载完成，共", Object.keys(wordData).length, "个单元");

// 确保wordData已全局可用
if (typeof window !== 'undefined') {
    window.wordData = wordData;
}
